language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vfor/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vfor/react-test npm test

after_sucess:
  - docker build -t vfor/multi-client ./client
  - docker build -t vfor/multi-nginx ./nginx
  - docker build -t vfor/multi-server ./server
  - docker build -t vfor/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images
  - docker push vfor/multi-client  
  - docker push vfor/multi-nginx 
  - docker push vfor/multi-server
  - docker push vfor/multi-worker


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-540155425372"
  bucket_path: "docker-multi"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
