language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vfor/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vfor/react-test npm test

after_sucess:
  - docker build -t vfor/multi-client -f ./client
  - docker build -t vfor/multi-nginx -f ./nginx
  - docker build -t vfor/multi-server -f ./server
  - docker build -t vfor/multi-worker -f ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images
  - docker push vfor/multi-client  
  - docker push vfor/multi-nginx 
  - docker push vfor/multi-server
  - docker push vfor/multi-worker
